# Generated by Django 6.0.3 on 2026-03-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorClimatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('agropecuario', 'Agropecuario'), ('agua', 'Agua'), ('bosques', 'Bosques')], max_length=20)),
                ('indicador', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
