# Generated by Django 6.0.3 on 2026-06-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo_tipo', models.CharField(max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('validating', 'Validando'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('published', 'Publicada')], default='pending', max_length=20)),
                ('validacion_mensaje', models.TextField(blank=True)),
                ('registros_afectados', models.IntegerField(default=0)),
                ('metadatos_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetadatoCapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capa', models.CharField(choices=[('departamentos', 'Departamentos'), ('capitales', 'Capitales'), ('lagos', 'Lagos'), ('rios', 'Ríos'), ('bosques', 'Bosques'), ('agropecuario', 'Agropecuario'), ('educativas', 'Unidades Educativas'), ('climatico', 'Datos Climáticos')], max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fuente', models.CharField(default='GeoBolivia / NASA', max_length=200)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('resolucion', models.CharField(blank=True, help_text='Ej: 250m, 500m, 1km', max_length=50)),
                ('extension', models.CharField(default='GeoJSON', max_length=20)),
                ('responsable', models.CharField(default='GeoBolivia', max_length=100)),
                ('url_descarga', models.URLField(blank=True)),
                ('url_metadatos', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StagingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('contenido_json', models.JSONField()),
                ('categoria', models.CharField(max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado_validacion', models.CharField(default='pending', max_length=50)),
                ('errores_validacion', models.TextField(blank=True)),
                ('registros_validos', models.IntegerField(default=0)),
                ('registros_invalidos', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='indicadorclimatico',
            name='anio',
        ),
        migrations.AlterField(
            model_name='indicadorclimatico',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indicadorclimatico',
            name='indicador',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='indicadorclimatico',
            name='municipio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='indicadorclimatico',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
